In [22]:
import var_selection
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [23]:
dataset = pd.read_csv('./data/happyness_data.csv', delimiter=' ')[['happy','money','sex','love','work']]
X = dataset[['money','sex','love','work']]
y = dataset[['happy']]
corrMat = X.corr()
print('Covariate sample correlation matrix:\n'+str(corrMat))

Covariate sample correlation matrix:
          money       sex      love      work
money  1.000000  0.306506  0.125815  0.067748
sex    0.306506  1.000000  0.047160 -0.316343
love   0.125815  0.047160  1.000000  0.385696
work   0.067748 -0.316343  0.385696  1.000000


In [24]:
[Evals, Evecs] = np.linalg.eig(corrMat)
print('Eigenvalues of Covariate sample correlation matrix: \n'+str(Evals))

Eigenvalues of Covariate sample correlation matrix: 
[ 0.44051911  0.735569    1.34680061  1.47711128]


In [25]:
X = np.concatenate([X.as_matrix(), np.ones([X.shape[0],1])], axis = 1)
y = y.as_matrix()

In [26]:
OLS_β = np.dot( np.linalg.inv(np.dot(X.T, X)), np.dot(X.T, y))
OLS_β_std = np.linalg.inv(np.dot(X.T, X))
print('Least squares coefficients: \n' + str(OLS_β[:-1]))
print('Least squares standard error: \n'+str(np.sqrt(np.diag(OLS_β_std[:,:-1]))))

Least squares coefficients: 
[[ 0.00957807]
 [-0.14900775]
 [ 1.91927907]
 [ 0.47607882]]
Least squares standard error: 
[ 0.00492533  0.39543257  0.27914964  0.18838761]


In [27]:
delta_happiness = 4.
delta_money = 50.
delta_sex = 0.5
delta_love = 1.
delta_work = 2.

In [28]:
τ_star = delta_happiness / np.array([delta_money,delta_sex,delta_love,delta_work])
print(τ_star)

[ 0.08  8.    4.    2.  ]


In [29]:
E = y - np.dot(X, OLS_β)

In [30]:
np.mean(E)

-1.0555658911051489e-14

In [31]:
β = np.zeros([5,1])
ϵ_squared = 2.5
p = np.concatenate([0.5 * np.ones([4,1]), np.zeros([1,1])])
τ = np.concatenate([np.atleast_2d(τ_star).T, 9 * np.ones([1,1])])
v = 0.01
ν = np.ones([5,1]) * 10e5
λ = np.concatenate([0.1*np.ones([1,1]), 10e10 * np.ones([4,1])])
iterations = 10

In [32]:
τ.shape

(5, 1)

In [33]:
"""
X: numpy.ndarray
y: numpy.ndarray
β: numpy.ndarray
ϵ_squared : scalar
p: iterable
τ: numpy.ndarray
v: scalar
ν: iterable
λ: iterable
iterations: scalar
"""
var_selection.variable_selection(X, y, β, ϵ_squared, p, τ, v, ν, λ, 10)

/usr/local/lib/python3.4/dist-packages/scipy/stats/_continuous_distns.py:4846: RuntimeWarning: divide by zero encountered in log
  self._logdelta = np.log(self._delta)
/home/soren/Studium/MonteCarlo/mcmc_proj7/var_selection.py:79: RuntimeWarning: invalid value encountered in multiply
  b = (X_j * z).sum() / X_sq_sum


ValueError: Domain error in arguments.

In [ ]:
X.shape